### ISSUE TITLE
Zone dependent Name resolution

### ISSUE THREAD

**Issue by cforce** [pivotal-cf/spring-cloud-services-connector#34]
Please see  https://github.com/spring-cloud/spring-cloud-netflix/issues/2545 for initial request in spring cloud netflix

**Comment by csterwa** [comment]
@habuma It looks like we have a reasonable solution the initial request for SCS specifically. I have prioritized this in our backlog.

**Comment by spikymonkey** [comment]
Can we refine this one further please?

There's a lot of discussion in that SCN issue, and it seems to raise quite a few questions. I agree with @habuma's point that by continually trying a direct app-to-container-IP connection that's blocked by network policies might end up worsening performance rather than improving it, so maybe this is behaviour we'd want to make configurable?

Also, Spencer has marked the original issue closed since Ribbon is going into maintenance mode. Which isn't to say we couldn't still do something in connectors, but possibly not using Ribbon?

What are the acceptance criteria for this story?
