### ISSUE TITLE
Add Support for Spring Boot 2.x.x

### ISSUE THREAD

**Issue by Bwvolleyball** [pivotal-cf/spring-cloud-services-connector#40]
Spring Boot 2 has changed a lot of the core framework of spring boot, including several things with the autowire process.

As a result, these connectors don't work in a spring boot 2 application as soon as it is deployed to PCF.

(Specifically, the Eureka binder crashes with a class not found exception because the relaxed property resolver been removed/moved/changed)

Exception:

Caused by: org.springframework.beans.factory.UnsatisfiedDependencyException: Error creating bean with name 'discoveryCompositeHealthIndicator' defined in class path resource [org/springframework/cloud/client/CommonsClientAutoConfiguration$DiscoveryLoadBalancerConfiguration.class]: Unsatisfied dependency expressed through method 'discoveryCompositeHealthIndicator' parameter 1; nested exception is org.springframework.beans.factory.UnsatisfiedDependencyException: Error creating bean with name 'eurekaHealthIndicator' defined in class path resource [org/springframework/cloud/netflix/eureka/EurekaClientAutoConfiguration$EurekaHealthIndicatorConfiguration.class]: Unsatisfied dependency expressed through method 'eurekaHealthIndicator' parameter 1; nested exception is org.springframework.beans.factory.BeanCreationException: Error creating bean with name 'eurekaInstanceConfigBean' defined in class path resource [io/pivotal/spring/cloud/service/eureka/EurekaInstanceAutoConfiguration.class]: Initialization of bean failed; nested exception is java.lang.NoClassDefFoundError: org/springframework/boot/bind/RelaxedPropertyResolver

this was produced with:
Spring Boot 2.0.0.RELEASE
And version 1.6.1.RELEASE of this repository's discovery client library

Ultimately, the Apex library is from this repo https://github.com/pivotal-cf/spring-cloud-services-starters for the spring-cloud-services-starter-service-registry project, however I have a hunch that the code update is needed in this project.  This problem probably impacts all the spring cloud services starters for PCF, I've just only tested it with Eureka.

**Comment by royclarkson** [comment]
Thanks for reporting. This work is in progress. Spring Cloud Services depends on open source Spring Cloud, which transitively depends on Spring Boot. While Spring Boot 2.0 has indeed gone GA, the compatible release of Spring Cloud has not. Spring Cloud Finchley M7 is the latest release with Spring Boot 2.0 support. A Spring Boot 2.0 compatible version of Spring Cloud Services cannot be released until Spring Cloud Finchley is GA.

**Comment by Bwvolleyball** [comment]
Thanks royclarkson,

Are there any plans or would it be possible to have a milestone or release candidate of these libraries that uses the latest milestone / release candidate of the Finchley series?
Then if there would be any issues, you could discover them before the final release as well! 😀

**Comment by csterwa** [comment]
@Bwvolleyball we don't have any plans to provide a milestone release since the impact of Spring Boot 2.0 as it is expressed through Spring Cloud Finchley may also cause API interaction issues with existing SCS services. We are planning to make both the SCS tile and connectors available around the same time. Currently we are targeting mid to late April due to the Boot 2.0 impact on our existing SCS tile codebase.

**Comment by shangal** [comment]
Upgrading the project https://github.com/spring-cloud-services-samples/greeting/tree/master/greeter 

for boot2 and spring-cloud-services-dependencies(2.0.0.M1) and Finchley.M9 i am getting the following error

[APP/PROC/WEB/0] [OUT] org.springframework.beans.factory.BeanCreationException: Error creating bean with name 'requestMappingHandlerMapping' defined in class path resource [org/springframework/boot/autoconfigure/web/servlet/WebMvcAutoConfiguration$EnableWebMvcConfiguration.class]: Invocation of init method failed; nested exception is java.lang.ArrayStoreException: sun.reflect.annotation.TypeNotPresentExceptionProxy

**Comment by springsource-readonly** [comment]
@shangal Did you remove the `1.4.2.RELEASE` version from this line https://github.com/spring-cloud-services-samples/greeting/blob/master/greeter/build.gradle#L32? 

There shouldn't be any version there - Boot should manage the version of that dependency. 

If that doesn't fix the problem, please create an issue in the `greeting` repo instead of adding to this closed issue.

**Comment by scottfrederick** [comment]
@shangal Did you remove the 1.4.2.RELEASE version from this line https://github.com/spring-cloud-services-samples/greeting/blob/master/greeter/build.gradle#L32?

There shouldn't be any version there - Boot should manage the version of that dependency.

If that doesn't fix the problem, please create an issue in the greeting repo instead of adding to this closed issue.

**Comment by shangal** [comment]
i was using the pom and i updated the versions to 2.0.0 - but thanks for the reply - i will go ahead and open the issue against the greeter project!
