### ISSUE TITLE
Getting an error in getting rabbitConnectionFactory when binding hystrix dashboard

### ISSUE THREAD

**Issue by bijukunjummen** [pivotal-cf/spring-cloud-services-connector#5]
I am getting a stack trace which looks like this when trying to bind Hystrix Dashboard service in a PCF environment - 

```
org.springframework.beans.factory.BeanCreationException: Error creating bean with name 'rabbitConnectionFactory' defined in class org.springframework.cloud.stream.binder.rabbit.config.RabbitServiceAutoConfiguration$CloudConfig: Bean insta
ntiation via factory method failed; nested exception is org.springframework.beans.BeanInstantiationException: Failed to instantiate [org.springframework.amqp.rabbit.connection.ConnectionFactory]: Factory method 'rabbitConnectionFactory' t
hrew exception; nested exception is org.springframework.cloud.CloudException: No unique service matching interface org.springframework.amqp.rabbit.connection.ConnectionFactory found. Expected 1, found 0
        at org.springframework.beans.factory.support.ConstructorResolver.instantiateUsingFactoryMethod(ConstructorResolver.java:599) ~[spring-beans-4.2.6.RELEASE.jar:4.2.6.RELEASE]
        at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.instantiateUsingFactoryMethod(AbstractAutowireCapableBeanFactory.java:1123) ~[spring-beans-4.2.6.RELEASE.jar:4.2.6.RELEASE]
        at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.createBeanInstance(AbstractAutowireCapableBeanFactory.java:1018) ~[spring-beans-4.2.6.RELEASE.jar:4.2.6.RELEASE]
        at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.doCreateBean(AbstractAutowireCapableBeanFactory.java:510) ~[spring-beans-4.2.6.RELEASE.jar:4.2.6.RELEASE]
```

It looks like the cloud-services-connector is not able to create a RabbitMQ related connection Factory and a downstream dependency ends up failing. This is specifically seen with version `1.1.0-RC1` of the connector and was working with version `1.0.1.RELEASE`.

Can you please check and see if I am missing something here.

**Comment by scottfrederick** [comment]
@bijukunjummen I assume you are using a `1.0.x` version of the Spring Cloud Services tile. With those versions of the tile you need to use `1.0.2.RELEASE` of the SCS connectors and starters. 

The `1.1.0` versions of the SCS connectors and starters are for compatibility with the upcoming `1.1.0` release of SCS. It is not possible to mix and match the "minor" versions between connectors/starters and the tile.

**Comment by bijukunjummen** [comment]
Ah, thanks @scottfrederick , that makes sense, at a client location we had downloaded a starter using start.spring.io site and it came pre-configured with the 1.1.0* version which had this issue. Yes, the tile is 1.0.*. I will make this change and keep in mind that the SCS connectors and tile versions are kept in sync.

**Comment by odedia** [comment]
I am getting the same exception with SCS 1.2.4 and Spring Cloud Connector that is extracted from Spring Cloud Brixton.SR7 --> 1.2.1.RELEASE. The exception is:

Thu Dec 29 2016 11:52:15 GMT+0200 (IST) [APP] OUT Caused by: org.springframework.beans.factory.BeanCreationException: Error creating bean with name 'rabbitConnectionFactory' defined in org.springframework.cloud.stream.binder.rabbit.config.RabbitServiceAutoConfiguration$CloudProfile$CloudConnectors$UseCloudConnectors: Bean instantiation via factory method failed; nested exception is org.springframework.beans.BeanInstantiationException: Failed to instantiate [org.springframework.amqp.rabbit.connection.ConnectionFactory]: Factory method 'rabbitConnectionFactory' threw exception; nested exception is org.springframework.cloud.CloudException: No unique service matching interface org.springframework.amqp.rabbit.connection.ConnectionFactory found. Expected 1, found 0

Note that this is the case whether I am binding a rabbitmq service in the manifest or not (Documentation is not clear if I need to bind rabbitmq or if it is automatic).

**Comment by bishoybasily** [comment]
i'm getting the same exception 

<spring-cloud-services.version>1.5.0.RELEASE</spring-cloud-services.version>
<spring-cloud.version>Dalston.SR3</spring-cloud.version>

Caused by: org.springframework.cloud.CloudException: No unique service matching interface org.springframework.amqp.rabbit.connection.ConnectionFactory found. Expected 1, found 0

**Comment by rgordiienko** [comment]
We're getting same exception
org.springframework.cloud:spring-cloud-starter-bus-amqp: -> 1.3.2.RC1
Spring cloud Edgware.RC1

**Comment by rgordiienko** [comment]
Sorry, issue was on our side, forgot to connect our app to upsi for rabbit mq through manifest
