### ISSUE TITLE
MongoTemplate Bean Creation Issue. 

### ISSUE THREAD

**Issue by azizabah** [pivotal-cf/spring-cloud-services-connector#97]
We're noticing an issue lately where applications will stand up fine locally but will not be able to stand up in PCF and the end result will end up being a lack of MongoTemplate bean. We've traced it down to the cloud connectors library but the exact issue is a bit beyond our current capabilities.

A sample project to reproduce is located [here](https://github.com/shane-jansen/spring-cloud-connectors-issue)

That project will deploy perfectly fine into PCF until you bind a user provided service with a mongodb connection string in it. As soon as you provide that, the MongoTemplate bean will fail to be created and the application will fail to stand up its application context.

**Comment by habuma** [comment]
That is an odd thing to have happen. However, you might get better results by posting this issue at https://github.com/spring-cloud/spring-cloud-connectors instead of here. That repo is where the support for binding Mongo services to your Spring Boot app is handled. 

The `spring-cloud-services-connector` project (e.g., this project) is for the connectors that support Spring Cloud Services (SCS), which is different from the Spring Cloud Connectors project. 

As I do not believe that your issue has anything to do with SCS, I'm going to close this issue. But if you disagree, please reopen and help me understand how it pertains to SCS.
